In [2]:
from sqlalchemy import create_engine,text
from urllib.parse import quote
import pandas as pd
from logzero import logger
# from SmartApi.smartConnect import SmartConnect
from sqlalchemy.exc import IntegrityError
import pyotp
import json
import re
import uuid
from uuid import UUID

In [3]:
stock_names = sorted(
    ["AARTIIND","ABB","ABBOTINDIA","ABCAPITAL","ABFRL","ACC","ADANIENSOL","ADANIENT","ADANIGREEN","ADANIPORTS","ALKEM","AMBUJACEM","ANGELONE","APLAPOLLO","APOLLOHOSP","APOLLOTYRE","ASHOKLEY","ASIANPAINT","ASTRAL","ATGL","ATUL","AUBANK","AUROPHARMA","AXISBANK","BAJAJ-AUTO","BAJAJFINSV","BAJFINANCE","BALKRISIND","BANDHANBNK","BANKBARODA","BANKINDIA","BATAINDIA","BEL","BERGEPAINT","BHARATFORG","BHARTIARTL","BHEL","BIOCON","BOSCHLTD","BPCL","BRITANNIA","BSE","BSOFT","CAMS","CANBK","CANFINHOME","CDSL","CESC","CGPOWER","CHAMBLFERT","CHOLAFIN","CIPLA","COALINDIA","COFORGE","COLPAL","CONCOR","COROMANDEL","CROMPTON","CUB","CUMMINSIND","CYIENT","DABUR","DALBHARAT","DEEPAKNTR","DELHIVERY","DIVISLAB","DIXON","DLF","DMART","DRREDDY","EICHERMOT","ESCORTS","EXIDEIND","FEDERALBNK","GAIL","GLENMARK","GMRAIRPORT","GNFC","GODREJCP","GODREJPROP","GRANULES","GRASIM","GUJGASLTD","HAL","HAVELLS","HCLTECH","HDFCAMC","HDFCBANK","HDFCLIFE","HEROMOTOCO","HFCL","HINDALCO","HINDCOPPER","HINDPETRO","HINDUNILVR","HUDCO","ICICIBANK","ICICIGI","ICICIPRULI","IDEA","IDFCFIRSTB","IEX","IGL","INDHOTEL","INDIAMART","INDIANB","INDIGO","INDUSINDBK","INDUSTOWER","INFY","IOC","IPCALAB","IRB","IRCTC","IRFC","ITC","JINDALSTEL","JIOFIN","JKCEMENT","JSL","JSWENERGY","JSWSTEEL","JUBLFOOD","KALYANKJIL","KEI","KOTAKBANK","KPITTECH","LALPATHLAB","LAURUSLABS","LICHSGFIN","LICI","LODHA","LT","LTF","LTIM","LTTS","LUPIN","M&M","M&MFIN","MANAPPURAM","MARICO","MARUTI","MAXHEALTH","MCX","METROPOLIS","MFSL","MGL","MOTHERSON","MPHASIS","MRF","MUTHOOTFIN","NATIONALUM","NAUKRI","NAVINFLUOR","NBCC","NCC","NESTLEIND","NHPC","NMDC","NTPC","NYKAA","OBEROIRLTY","OFSS","OIL","ONGC","PAGEIND","PAYTM","PEL","PERSISTENT","PETRONET","PFC","PHOENIXLTD","PIDILITIND","PIIND","PNB","POLICYBZR","POLYCAB","POONAWALLA","POWERGRID","PRESTIGE","PVRINOX","RAMCOCEM","RBLBANK","RECLTD","RELIANCE","SAIL","SBICARD","SBILIFE","SBIN","SHREECEM","SHRIRAMFIN","SIEMENS","SJVN","SOLARINDS","SONACOMS","SRF","SUNPHARMA","SUNTV","SUPREMEIND","SYNGENE","TATACHEM","TATACOMM","TATACONSUM","TATAELXSI","TATAMOTORS","TATAPOWER","TATASTEEL","TCS","TECHM","TIINDIA","TITAN","TORNTPHARM","TORNTPOWER","TRENT","TVSMOTOR","UBL","ULTRACEMCO","UNIONBANK","UNITDSPR","UPL","VBL","VEDL","VOLTAS","WIPRO","YESBANK","ZOMATO","ZYDUSLIFE"], key=len, reverse=True)
NAMESPACE_STOCK = UUID('233c16a9-0a91-4c9d-adda-8a496c63a1a3')

# expiry_dates = ['2024-07-25']
# api_key = 'BP42pHUk'
# username = 'R60865380'
# pwd = '6713'
# smartApi = SmartConnect(api_key)

engine = create_engine(
        "postgresql+psycopg2://sd_admin:%s@192.168.1.72:5430/stock-dumps"
        % quote("sdadmin@postgres")
    )

In [3]:
try:
    token = "ARA7CTUQBDWODFCWKVSAXTLR4U"
    totp = pyotp.TOTP(token).now()
except Exception as e:
    logger.error("Invalid Token: The provided token is not valid.")
    raise e

correlation_id = "abcde"
data = smartApi.generateSession(username, pwd, totp)
def categorize_tradingsymbol(row, stock_names):
    for name in stock_names:
        if re.match(f"^{name}", row['tradingsymbol']):
            return name
    return None
searchScripData_df = pd.DataFrame({})
if data['status'] == False:
    logger.error(data)
else:
    # logger.info(f"data: {data}")
    authToken = data['data']['jwtToken']
    refreshToken = data['data']['refreshToken']
    feedToken = smartApi.getfeedToken()
    # logger.info(f"Feed-Token :{feedToken}")
    res = smartApi.getProfile(refreshToken)
    # logger.info(f"Get Profile: {res}")
    smartApi.generateToken(refreshToken)
    res=res['data']['exchanges']
    #search for symbol
    exchange = "NFO"
    searchscrip = "ABBOTINDIA"
    searchScripData = smartApi.searchScrip(exchange, searchscrip)
    df = pd.DataFrame(
        searchScripData["data"], columns=["exchange", "tradingsymbol", "symboltoken"]
    )
    df['stock_name'] = df.apply(categorize_tradingsymbol, stock_names=stock_names, axis=1)
    searchScripData_df = df[df["tradingsymbol"].str.contains('AUG')
            & ~df["tradingsymbol"].str.contains("FUT")
            & ~df.duplicated(["symboltoken"])]
    print(searchScripData_df)

NameError: name 'smartApi' is not defined

In [11]:
df[df['tradingsymbol'].str.contains('28000')]

    exchange             tradingsymbol symboltoken  stock_name
82       NFO  ABBOTINDIA26SEP2428000CE       90529  ABBOTINDIA
83       NFO  ABBOTINDIA26SEP2428000PE       90530  ABBOTINDIA
254      NFO  ABBOTINDIA29AUG2428000PE       77255  ABBOTINDIA
383      NFO  ABBOTINDIA31OCT2428000CE       63535  ABBOTINDIA
384      NFO  ABBOTINDIA31OCT2428000PE       63536  ABBOTINDIA

In [10]:
searchScripData_df[searchScripData_df['tradingsymbol'].str.contains('28000')]

    exchange             tradingsymbol symboltoken  stock_name
254      NFO  ABBOTINDIA29AUG2428000PE       77255  ABBOTINDIA

In [16]:
def query_to_dataframe(query, connection):
    result = connection.execute(text(query))
    rows = result.fetchall()
    columns = result.keys()
    return pd.DataFrame(rows, columns=columns)

# Connect to the database
with engine.connect() as connection:
    # Query to select all from the 'stock' table
    stock_df = query_to_dataframe("SELECT * FROM options.stock", connection)

In [12]:
searchScripData_df
# create ticker df 
# symbol_token stock_id expiry_date strike_price option_type

ticker_df = pd.DataFrame(
    columns=["symbol_token", "stock_id", "expiry_date", "strike_price", "option_type"]
)
ticker_df['symbol_token'] = searchScripData_df['symboltoken']
ticker_df['stock_id'] = 
print(ticker_df)

Empty DataFrame
Columns: [symbol_token, stock_id, expiry_date, strike_price, option_type]
Index: []

In [4]:
# create stocks df
# name nifty_fifty_index
df = pd.DataFrame(
        {'name':stock_names, 'nifty_fifty_index':0}
    )
df['id'] = [uuid.uuid5(NAMESPACE_STOCK,s) for s in stock_names]
print(df)

           name  nifty_fifty_index                                    id
0    ABBOTINDIA                  0  13512523-55e9-57e4-9e0c-22fd88120b84
1    ADANIENSOL                  0  f0b80aa4-41b6-5acb-8dd8-94136daafed7
2    ADANIGREEN                  0  ba6f2f97-ec2b-594d-ad99-4262422bd03e
3    ADANIPORTS                  0  6396eba1-a7df-5169-8ace-1611c5d12a22
4    APOLLOHOSP                  0  f22055cc-136c-5f1c-9117-30ecf02ead7a
..          ...                ...                                   ...
222         TCS                  0  ed5e8f3c-cd82-587a-a598-c4f6eae04380
223         UBL                  0  66aedc2e-97d6-5d9b-9d15-66d348f2a110
224         UPL                  0  98160b98-f2ad-5306-8c05-9b9d1b734fb9
225         VBL                  0  5da52481-9de8-5408-80c3-e8c7176f9ef1
226          LT                  0  754217d7-4b2a-5af8-9c72-31a14a28fbc3

[227 rows x 3 columns]

In [5]:
# insert into stock table
# get existing data
existing = pd.read_sql_query("SELECT * FROM options.stock", con=engine)
# compare with new data and filter the latest
newStocks = df[~df["id"].isin(existing["id"])]
# print(newStocks["name"])
# push newStocks
newStocks.to_sql("stock", schema="options", if_exists="append", con=engine, index=False)

5

In [12]:
read expiry, stock to a df
with engine.connect() as connection:
    result = connection.execute(text("SELECT * FROM options.stock"))
    rows = result.fetchall()
    columns = result.keys()
df = pd.DataFrame(rows, columns=columns)
print(df)

     stock_id        name  nifty_fifty_index
0           1  ABBOTINDIA                  0
1           2  ADANIPORTS                  0
2           3  APOLLOHOSP                  0
3           4  APOLLOTYRE                  0
4           5  ASIANPAINT                  0
..        ...         ...                ...
176       177         SRF                  0
177       178         TCS                  0
178       179         UBL                  0
179       180         UPL                  0
180       181          LT                  0

[181 rows x 3 columns]